# Generated by Django 6.1.1 on 2026-09-18 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("venues", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("music", "Music"),
                            ("technology", "Technology"),
                            ("art", "Art"),
                            ("sport", "Sport"),
                            ("education", "Education"),
                            ("business", "Business"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                (
                    "banner",
                    models.ImageField(
                        blank=True, null=True, upload_to="events/banners/"
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "organizer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="venues.venue",
                    ),
                ),
            ],
            options={
                "ordering": ["start_at"],
            },
        ),
        migrations.CreateModel(
            name="TicketType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=250)),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("capacity", models.PositiveIntegerField()),
                ("max_per_booking", models.PositiveIntegerField(default=5)),
                ("sales_start_at", models.DateTimeField(blank=True, null=True)),
                ("sales_end_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ticket_types",
                        to="events.event",
                    ),
                ),
            ],
            options={
                "ordering": ["price"],
            },
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["status"], name="events_even_status_5709b6_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["category"], name="events_even_categor_aca11d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["start_at"], name="events_even_start_a_268ef9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["status", "start_at"], name="events_even_status_76ecd8_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_at__gt", models.F("start_at"))),
                name="event_end_after_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="tickettype",
            constraint=models.UniqueConstraint(
                fields=("event", "name"), name="unique_ticket_type_name_per_event"
            ),
        ),
        migrations.AddConstraint(
            model_name="tickettype",
            constraint=models.CheckConstraint(
                condition=models.Q(("price__gte", 0)), name="ticket_price_gte_zero"
            ),
        ),
        migrations.AddConstraint(
            model_name="tickettype",
            constraint=models.CheckConstraint(
                condition=models.Q(("capacity__gt", 0)), name="ticket_capacity_gt_zero"
            ),
        ),
        migrations.AddConstraint(
            model_name="tickettype",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_per_booking__gt", 0)),
                name="ticket_max_per_booking_gt_zero",
            ),
        ),
    ]
