# Generated by Django 6.1.1 on 2026-09-18 19:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Venue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("country", models.CharField(default="Iran", max_length=100)),
                ("city", models.CharField(default="Tehran", max_length=100)),
                ("address", models.TextField()),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum physical capacity of the venue.",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_venues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["city"], name="venues_venu_city_4d7e2f_idx"),
                    models.Index(
                        fields=["is_active"], name="venues_venu_is_acti_954204_idx"
                    ),
                ],
            },
        ),
    ]
