# Generated by Django 6.1.1 on 2026-10-02 19:48

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venue',
            options={'ordering': ['name', 'id']},
        ),
        migrations.RemoveIndex(
            model_name='venue',
            name='venues_venu_city_4d7e2f_idx',
        ),
        migrations.AlterField(
            model_name='venue',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum physical capacity of the venue.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['city', 'is_active'], name='venues_venu_city_a4d9c1_idx'),
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['country', 'city'], name='venues_venu_country_d414c9_idx'),
        ),
        migrations.AddConstraint(
            model_name='venue',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__isnull', True), ('capacity__gt', 0), _connector='OR'), name='venues_capacity_gt_zero_or_null'),
        ),
    ]
